# Generated by Django 3.2 on 2021-05-16 09:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='from_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
